### PR TITLE
Refactor:  Update ontology viewer from old JS to Turbo + Stimulus 

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
# Prerequisite

- https://github.com/ncbo/bioportal_web_ui/pull/201

# What and why
This PR **simplifies and updates our current JS code, by removing 814 lines of JS code but still keeping the same behaviors and features**. 

It's possible using the two following tools: 
- _Tubro frame:_ will use Ajax to send and replace the HTML in a specified part of the current page (without reloading and JS code), this will replace most parts of our current JS code that are exactly doing that.
- _Stimulus JS:_ will centralize/isolate js code, so that we can reuse it more easily and avoid duplication and unused/forgotten code (a problem that we have a lot currently).  
# After the PR 
https://user-images.githubusercontent.com/29259906/191605775-9ebce4d8-773a-4991-8b3a-33de4124628b.mov

# Changes

- Replace bp_ontology_viewer.js with turbo frame in the ontology viewer  ( **same behavior with 417 (JS) lines less**)(https://github.com/ncbo/bioportal_web_ui/commit/9371bc41ed43882b8aa0b8fa129e94ef8c5acea0)
     - remove file  bp_ontology_viewer.js (403 lines of js code less)
     - replace bp_ontology_viewer.js with lazy load frame (details see https://turbo.hotwired.dev/reference/frames#lazy-loaded-frame)
     - simplify layouts/_ontology_viewer.html.haml file by extracting common code  in a loop (32 lines of HTML less)
    
- Fix visits chart not showing( (see https://github.com/ncbo/bioportal_web_ui/issues/179) https://github.com/ncbo/bioportal_web_ui/commit/f73f7fceb2e6d056994e7bb3de778d9f2a1782cc)
     - replacing app/assets/javascripts/ontologies.js with a stimulus controller "load-chart" 
- Fix more... submission button that was not working     (https://github.com/ncbo/bioportal_web_ui/commit/4e06e29b4ab678ef0a0a89bf35e63dfb15ebc21a)
     -  clicking in the 'more...' will show the full table of submissions and replace the "more..." text with "less..." (and vis-versa)
- Remove empty functions in app/assets/javascripts/bp_notes.js (**10 lines less**) (https://github.com/ncbo/bioportal_web_ui/commit/0987e08c0d7a928d7f2a60e894eb00f9d755a1a4)
- Fix notes unsubscribe button (https://github.com/ncbo/bioportal_web_ui/commit/d21c570bb591686d87946fbbe06f56cc3bd874e7)
- Replace concepts tree view node click js code with turbo_frames (**same behavior with 259 (JS) lines less**)
   -   Add a partial and route to show concept information (details, visualization, mappings, request_term), extracted from app/views/ontologies/visualize.html.haml
 (https://github.com/ncbo/bioportal_web_ui/commit/9c7d3a2d5a5b16ced2045fc2a56a8ee95dc36af8)
   - Fix concept mappings count not showing (see issue 3 of https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/80) (https://github.com/ncbo/bioportal_web_ui/commit/9c7d3a2d5a5b16ced2045fc2a56a8ee95dc36af8)
   -  Remove 250 JS lines in app/assets/javascripts/bp_class_tree.js.erb replaced with trubo_frame 
- Update and centralize Split dependency  (**17 JS code less**) (https://github.com/ncbo/bioportal_web_ui/commit/a8e029be3e6944fca2ef8d8c4dd4036b0d39af7b)
   - install split with yarn (js package manager) and remove lines that upload it  `<script src="//unpkg.com/split.js/dist/split.min.js">`
   - centralize the split usage inside a stimulus controller called "container-splitter"
- Centralize Simple tree dependency  and replace JS code that displays the treeview with a turbo frame (**41 JS code less**) (https://github.com/ncbo/bioportal_web_ui/commit/675c4f3d3074a9df5c440dc0e0856f56982d8c10)
   - remove/move the file app/assets/javascripts/bp_class_tree.js.erb (82 lines of js code)
   - centralize the simple tree view usage inside a stimulus controller called "simple-tree"
   - use a turbo_frame in app/views/ontologies/visualize.html.haml to display the tree view
   - remove unused function in  app/assets/javascripts/bioportal.js.erb (16 lines less)
- Extract/centralize autocomplete behavior in a stimulus controller   (https://github.com/ncbo/bioportal_web_ui/commit/ecfa8caded13a7d535787be0bea631818aa8471e)
  - remove/move the code that does the `jump to a concept` feature from app/assets/javascripts/bp_visualize.js.erb to a stimulus controller (87 lines of JS code)
- Replace the js code responsible for showing concepts tabs with bootstrap tabs  ( **70 lines js code less** )(https://github.com/ncbo/bioportal_web_ui/commit/6910d785f617c76ba15d54514df82959c2296c7c)
   - remove file app/assets/javascripts/bp_visualize.js.erb 
   - use bootstrap navs (see https://getbootstrap.com/docs/4.3/components/navs/#tabs)

### CODE REVIEW

**Comment by jvendetti** [comment]
Hi @syphax-bouazzouni - thanks for the pull request. I'm interested in moving forward on this one, but I realize that a fair amount of time has gone by since it was submitted. Is your AgroPortal code base still relatively in alignment with the changes you made here?

**Comment by jvendetti** [comment]
I also wonder if you'd be willing to drop the commits from this pull request from May 25 - 28 that perform the Rails 7 upgrade?

**Comment by jvendetti** [comment]
I'm testing this pull request in my local dev environment. I've run into a variety of issues, so I'm building a list here for what I need to fix before I can merge this into our master branch.

- [x] Navigating to any ontology throws an `undefined method escape` error
- [ ] Navigating to any ontology throws a `No route matches` error for a `fetch_results` action
- [ ] The top-level tabs on the ontology landing pages don't work properly unless you click on the Summary tab. After the first click on the Summary tab, then they work as expected. If you don't click the Summary tab, clicking on any of the other tabs doesn't do anything.
- [ ] Navigating to any ontology marked as flat (e.g. MEDDRA) results in a 500 internal server error, for URLs like this: http://localhost:3000/ajax/classes/treeview?concept=bp_fake_root&ontology=MEDDRA
- [ ] The Classes pane for flat ontologies (e.g. MEDDRA) perpetually displays a loading message underneath the Jump to text area
- [ ] The top-level Widgets tabs for all ontologies is blank
- [ ] For all ontologies, only the Details sub-tab works. All others (Visualization, Notes, Class Mappings) don't respond to clicks - this is Bootstrap-related.

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal can you do the follow-up of this?

**Comment by Bilelkihal** [comment]
> @Bilelkihal can you do the follow-up of this?

Okay

**Comment by jvendetti** [comment]
Mutually agreed with submitter to close - too much time went by between original submission date and initial attempt to merge

**Pull request closed without merging**
